EthicsCap2/Models/Camels/AssetQualityAssessment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace EthicsCap2.Models.Camels
{
    public class AssetQualityAssessment
    {
        [Range(0, 5, ErrorMessage = "Must be between 0 to 5")]
        public int CapitalAdequacyRating { get; set; }
        [Range(0, 5, ErrorMessage = "Must be between 0 to 5")]
        public int AdverselyClassifiedItemsRatio { get; set; }
        [Range(0, 5, ErrorMessage = "Must be between 0 to 5")]
        public int AssetQualityQuestion1 { get; set; }
        [Range(0, 5, ErrorMessage = "Must be between 0 to 5")]
        public int AssetQualityQuestion2 { get; set; }
        [Range(0, 5, ErrorMessage = "Must be between 0 to 5")]
        public int AssetQualityQuestion3 { get; set; }

        public int CompositeAverage { get; set; }
    }
}

EthicsCap2/Models/Camels/AssetQualityCapitalAssessment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace EthicsCap2.Models.Camels
{
    public class AssetQualityCapitalAssessment
    {
        [Range(0, 5, ErrorMessage = "Must be between 0 to 5")]
        public int AssetQualityRating { get; set; }
        [Range(0, 5, ErrorMessage = "Must be between 0 to 5")]
        public int AdverselyClassifiedItemsRatio { get; set; }


        [Range(0, 5, ErrorMessage = "Must be between 0 to 5")]
        public int RegulatoryLeadership { get; set; }
        [Range(0, 5, ErrorMessage = "Must be between 0 to 5")]
        public int RegulatoryResources { get; set; }
        [Range(0, 5, ErrorMessage = "Must be between 0 to 5")]
        public int RegulatoryProcesses { get; set; }
        [Range(0, 5, ErrorMessage = "Must be between 0 to 5")]
        public int RegulatoryCulture { get; set; }

        [Range(0, 5, ErrorMessage = "Must be between 0 to 5")]
        public int TotalAssetRegulatoryScore { get; set; }
    }
}

EthicsCap2/Models/Camels/CapitalAdequacyAssessment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace EthicsCap2.Models.Camels
{
    public class CapitalAdequacyAssessment
    {
        [Range(0, 5, ErrorMessage = "Must be between 0 to 5")]
        public int CapitalAdequacyRating { get; set; }
        [Range(0, 5, ErrorMessage = "Must be between 0 to 5")]
        public int Tier1CapitalRatio { get; set; }
        [Range(0, 5, ErrorMessage = "Must be between 0 to 5")]
        public int TotalCapitalRatio { get; set; }
        [Range(0, 5, ErrorMessage = "Must be between 0 to 5")]
        public int CapitalAdequacyQuestion1 { get; set; }
        [Range(0, 5, ErrorMessage = "Must be between 0 to 5")]
        public int CapitalAdequacyQuestion2 { get; set; }
        [Range(0, 5, ErrorMessage = "Must be between 0 to 5")]
        public int CapitalAdequacyQuestion3 { get; set; }

        public int CompositeAverage { get; set; }
}
}

EthicsCap2/Models/Camels/CapitalAdequacyCapitalAssessment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace EthicsCap2.Models.Camels
{
    public class CapitalAdequacyCapitalAssessment
    {
        
        [Range(0, 5, ErrorMessage = "Must be between 0 to 5")]
        public int AssetQualityRating { get; set; }
        [Range(0, 5, ErrorMessage = "Must be between 0 to 5")]
        public int AdverselyClassifiedItemsRatio  { get; set; }


        [Range(0, 5, ErrorMessage = "Must be between 0 to 5")]
        public int RegulatoryLeadership { get; set; }
        [Range(0, 5, ErrorMessage = "Must be between 0 to 5")]
        public int RegulatoryResources   { get; set; }
        [Range(0, 5, ErrorMessage = "Must be between 0 to 5")]
        public int RegulatoryProcesses   { get; set; }
        [Range(0, 5, ErrorMessage = "Must be between 0 to 5")]
        public int RegulatoryCulture { get; set; }

        [Range(0, 5, ErrorMessage = "Must be between 0 to 5")]
        public int TotalCapitalRegulatoryScore { get; set; }
    }
}

EthicsCap2/Models/Camels/EarningsStabilityAssessment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace EthicsCap2.Models.Camels
{
    public class EarningsStabilityAssessment
    {

        [Range(0, 5, ErrorMessage = "Must be between 0 to 5")]
        public int EarningsStabilityRating { get; set; }
        [Range(0, 5, ErrorMessage = "Must be between 0 to 5")]
        public int ROAA { get; set; }
         [Range(0, 5, ErrorMessage = "Must be between 0 to 5")]
        public int EarningsStabilityQuestion1 { get; set; }
        [Range(0, 5, ErrorMessage = "Must be between 0 to 5")]
        public int EarningsStabilityQuestion2 { get; set; }
        [Range(0, 5, ErrorMessage = "Must be between 0 to 5")]
        public int EarningsStabilityQuestion3 { get; set; }

        public int CompositeAverage { get; set; }
    }
}

EthicsCap2/Models/Camels/EarningsStabilityCapitalRegulatoryAssessment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace EthicsCap2.Models.Camels
{
    public class EarningsStabilityCapitalRegulatoryAssessment
    {

        [Range(0, 5, ErrorMessage = "Must be between 0 to 5")]
        public int EarningsSustainabilityRating { get; set; }
        [Range(0, 5, ErrorMessage = "Must be between 0 to 5")]
        public int ROAA { get; set; }

        [Range(0, 5, ErrorMessage = "Must be between 0 to 5")]
        public int RegulatoryLeadership { get; set; }
        [Range(0, 5, ErrorMessage = "Must be between 0 to 5")]
        public int RegulatoryResources { get; set; }
        [Range(0, 5, ErrorMessage = "Must be between 0 to 5")]
        public int RegulatoryProcesses { get; set; }
        [Range(0, 5, ErrorMessage = "Must be between 0 to 5")]
        public int RegulatoryCulture { get; set; }

        [Range(0, 5, ErrorMessage = "Must be between 0 to 5")]
        public int TotalEarningsStabilityRegulatoryScore { get; set; }
    }
}

EthicsCap2/Models/Camels/LiquidityRiskAssessment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace EthicsCap2.Models.Camels
{
    public class LiquidityRiskAssessment
    {
        [Range(0, 5, ErrorMessage = "Must be between 0 to 5")]
        public int LiquidityRiskRating { get; set; }
        [Range(0, 5, ErrorMessage = "Must be between 0 to 5")]
        public int AdverselyStressedLiquidityRating { get; set; }
        [Range(0, 5, ErrorMessage = "Must be between 0 to 5")]
        public int LiquidityRiskQuestion1 { get; set; }
        [Range(0, 5, ErrorMessage = "Must be between 0 to 5")]
        public int LiquidityRiskQuestion2 { get; set; }
        [Range(0, 5, ErrorMessage = "Must be between 0 to 5")]
        public int LiquidityRiskQuestion3 { get; set; }

        public int CompositeAverage { get; set; }
    }
}

EthicsCap2/Models/Camels/LiquidityRiskRegulatoryAssessment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace EthicsCap2.Models.Camels
{
    public class LiquidityRiskRegulatoryAssessment
    {
        [Range(0, 5, ErrorMessage = "Must be between 0 to 5")]
        public int LiquidityRiskRating { get; set; }
        [Range(0, 5, ErrorMessage = "Must be between 0 to 5")]
        public int AdverselyStressedLiquidityRatio  { get; set; }

        [Range(0, 5, ErrorMessage = "Must be between 0 to 5")]
        public int RegulatoryLeadership { get; set; }
        [Range(0, 5, ErrorMessage = "Must be between 0 to 5")]
        public int RegulatoryResources { get; set; }
        [Range(0, 5, ErrorMessage = "Must be between 0 to 5")]
        public int RegulatoryProcesses { get; set; }
        [Range(0, 5, ErrorMessage = "Must be between 0 to 5")]
        public int RegulatoryCulture { get; set; }

        [Range(0, 5, ErrorMessage = "Must be between 0 to 5")]
        public int TotalLiquidityRiskRegulatoryScore { get; set; }
    }
}

EthicsCap2/Models/Camels/ManagementEffectivenessAssessment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace EthicsCap2.Models.Camels
{
    public class ManagementEffectivenessAssessment
    {

        [Range(0, 5, ErrorMessage = "Must be between 0 to 5")]
        public int ManagementEffectivenessRating { get; set; }
        [Range(0, 5, ErrorMessage = "Must be between 0 to 5")]
        public int CRARating { get; set; }
        [Range(0, 5, ErrorMessage = "Must be between 0 to 5")]
        public int EfficeincyRatio { get; set; }
        [Range(0, 5, ErrorMessage = "Must be between 0 to 5")]
        public int ManagementEffectivenessQuestion1 { get; set; }
        [Range(0, 5, ErrorMessage = "Must be between 0 to 5")]
        public int ManagementEffectivenessQuestion2 { get; set; }
        [Range(0, 5, ErrorMessage = "Must be between 0 to 5")]
        public int ManagementEffectivenessQuestion3 { get; set; }

        public int CompositeAverage { get; set; }
    }
}

EthicsCap2/Models/Camels/ManagementEffectivenessCapitalAssessment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace EthicsCap2.Models.Camels
{
    public class ManagementEffectivenessCapitalAssessment
    {
        [Range(0, 5, ErrorMessage = "Must be between 0 to 5")]
        public int ManagementEffectivenessRating { get; set; }
        [Range(0, 5, ErrorMessage = "Must be between 0 to 5")]
        public int EfficiencyRatio { get; set; }


        [Range(0, 5, ErrorMessage = "Must be between 0 to 5")]
        public int RegulatoryLeadership { get; set; }
        [Range(0, 5, ErrorMessage = "Must be between 0 to 5")]
        public int RegulatoryResources { get; set; }
        [Range(0, 5, ErrorMessage = "Must be between 0 to 5")]
        public int RegulatoryProcesses { get; set; }
        [Range(0, 5, ErrorMessage = "Must be between 0 to 5")]
        public int RegulatoryCulture { get; set; }

        [Range(0, 5, ErrorMessage = "Must be between 0 to 5")]
        public int TotalMgmtEffectivenessRegulatoryScore { get; set; }
    }
}

EthicsCap2/Models/Camels/OverallCapitalIQ.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace EthicsCap2.Models.Camels
{
    public class OverallCapitalIQ
    {
        [Range(0, 5, ErrorMessage = "Must be between 0 to 5")]
        public int EnterValue { get; set; }

    }
}

EthicsCap2/Models/Camels/OverallRegulatoryCapitalScores.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EthicsCap2.Models.Camels
{
    public class OverallRegulatoryCaptialScores
    {
        public double CapitalAdequacyRating { get; set; }
        public double AssetQualityRating { get; set; }
        public double ManagementEffectivenessRating { get; set; }
        public double EarningsSustainableRating { get; set; }
        public double LiquidityRiskRating { get; set; }
        public double SensitivitytoMarketRiskRating { get; set; }
        

        public double AverageRegulatoryLeadership { get; set; }
        public double AverageRegulatoryResources { get; set; }
        public double AverageRegulatoryProcesses { get; set; }
        public double AverageRegulatoryCulture { get; set; }

        public double TotalRegulatoryScore { get; set; }
    }
}

EthicsCap2/Models/Camels/OverallRegulatoryScores.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EthicsCap2.Models.Camels
{
    public class OverallRegulatoryScores
    {
    public double CapitalAdequacyRating { get; set; }
    public double AssetQualityRating { get; set; }
    public double ManagementEffectivenessRating { get; set; }
    public double EarningsSustainableRating { get; set; }
    public double LiquidityRiskRating { get; set; }
    public double SensitivitytoMarketRiskRating { get; set; }
    public double CompositeRegulatoryKnowledge { get; set; }
    }
}

EthicsCap2/Models/Camels/RegulatoryKnowledgeAssessment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace EthicsCap2.Models.Camels
{
    public class RegulatoryKnowledgeAssessment
    {
        [Range(0, 5, ErrorMessage = "Must be between 0 to 5")]
        public int CapitalAdequacyRating { get; set; }
        [Range(0, 5, ErrorMessage = "Must be between 0 to 5")]
        public int AssestQualityRating { get; set; }
        [Range(0, 5, ErrorMessage = "Must be between 0 to 5")]
        public int ManagementEffectivenessRating { get; set; }
        [Range(0, 5, ErrorMessage = "Must be between 0 to 5")]
        public int CRAandTargetExamRatings { get; set; }
        [Range(0, 5, ErrorMessage = "Must be between 0 to 5")]
        public int EarningsSustainabilityRating { get; set; }
        [Range(0, 5, ErrorMessage = "Must be between 0 to 5")]
        public int LiquidityRiskRating { get; set; }
        [Range(1, 5, ErrorMessage = "Must be between 0 to 5")]
        public int SensitivitytoMarketRiskRating { get; set; }
        [Range(0, 5, ErrorMessage = "Must be between 0 to 5")]
        public int Tier1CapitalRatio { get; set; }
        [Range(0, 5, ErrorMessage = "Must be between 0 to 5")]
        public int TotalCapitalRatio { get; set; }
        [Range(0, 5, ErrorMessage = "Must be between 0 to 5")]
        public int AdverselyClassifiedItemsRatio { get; set; }
        [Range(0, 5, ErrorMessage = "Must be between 0 to 5")]
        public int EfficiencyRatio { get; set; }
        [Range(0, 5, ErrorMessage = "Must be between 0 to 5")]
        public int ROAA { get; set; }
        [Range(0, 5, ErrorMessage = "Must be between 0 to 5")]
        public int AdverselyStressedLiquidity { get; set; }
        [Range(0, 5, ErrorMessage = "Must be between 0 to 5")]
        public int AdverselyStressedNIM { get; set; }

    }
}

EthicsCap2/Controllers/CamelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace EthicsCap2.Controllers
{
    public class CamelController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        
        public IActionResult RegulatoryKnowledgeAssessment()
        {
            return View();
        }
        public IActionResult CapitalAdequacyAssessment()
        {
            return View();
        }
        public IActionResult LiquidityRiskAssessment()
        {
            return View();
        }
        public IActionResult AssetQualityAssessment()
        {
            return View();
        }
        public IActionResult TargetedOutcomes()
        {
            return View();
        }

        public IActionResult ManagementEffectivenessAssessment()
        {
            return View();
        }


        public IActionResult EarningsStabilityAssessment()
        {
            return View();
        }

        public IActionResult SensitivityToMarketRiskAssessment()
        {
            return View();
        }

        public IActionResult OverallRegulatoryKnowledge()
        {
            return View();
        }

        /// <summary>
        /// Regulatory Capture
        /// </summary>
        /// <returns></returns>

        public IActionResult Regulatory1()
        {
            return View();
        }
        public IActionResult Regulatory2()
        {
            return View();
        }
        public IActionResult Regulatory3()
        {
            return View();
        }

        public IActionResult RegulatoryCapitalAssessment()
        {
            return View();
        }

        /////////////////////////////////////////////////////
        public IActionResult CapitalAdequacyCapitalAssessment()
        {
            return View();
        }
        public IActionResult LiquidityRiskRegulatoryAssessment()
        {
            return View();
        }
        public IActionResult AssestQuaityCapitalAssessment()
        {
            return View();
        }
        public IActionResult TargetedCapitalOutcomes()
        {
            return View();
        }

        public IActionResult ManagementEffectivenessCapitalAssessment()
        {
            return View();
        }


        public IActionResult EarningsStabilityCapitalRegulatoryAssessment()
        {
            return View();
        }

        public IActionResult SensitivityToMarketRegulatoryAssessment()
        {
            return View();
        }
        
        public IActionResult OverallRegulatoryCapitalAssessment()
        {
            return View();
        }
        ////////////////////////
        ///
        
        public IActionResult CalculatingRegulatoryIQ()
        {
            return View();
        }


        public IActionResult OveralRelationKnowledge1()
        {
            return View();
        }


        public IActionResult OveralRelationKnowledge2()
        {
            return View();
        }

        
    }
}

EthicsCap2/Views/Camel/AssestQuaityCapitalAssessment.cshtml
@model EthicsCap2.Models.Camels.AssetQualityCapitalAssessment

@{
    ViewData["Title"] = "AssestQuaityCapitalAssessment";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <h1>Assest Quality Regulatory Capital Assessment</h1>

    <div class="form-horizontal">
        <h2>Assest Quality Regulatory</h2>
        <hr />
        <table class="table table-bordered table-responsive table-hover d-xl-table">

            <tr>
                <th rowspan="1" colspan="2">
                    Targeted Regulatory Outcomes
                </th>
                <th rowspan="1" colspan="4">Regulatory Capital Dimensions</th>
            </tr>
            <tr>
                <td rowspan="1" align="center">
                    Targeted Regulatory Exam Outcomes:
                    <br />
                    <br />
                    Assest Quality Rating
                    @Html.EditorFor(model => model.AssetQualityRating, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.AssetQualityRating, "", new { @class = "text-danger" })
                </td>
                <td rowspan="1" align="center">
                    Targeted Financial/Risk Outcomes:
                    <br />
                    <br />
                    Adversely Classified Items Ratio <                                 >
                    @Html.EditorFor(model => model.AdverselyClassifiedItemsRatio, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.AdverselyClassifiedItemsRatio, "", new { @class = "text-danger" })
                </td>
                <td>
                    Right Regulatory Leadership

                </td>
                <td>
                    Sufficient Regulatory Resources

                </td>
                <td>
                    Accountable Regulatory Processes
                </td>
                <td>
                    Effective Regulator Culture

                </td>
            </tr>
            <tr>
                <td rowspan="2" colspan="2">
                    <ul>
                        <li>
                            Regulatory Evaluation Factors for Determining Asset Quality Exam Rating:
                        </li>
                        <li>Overall Financial Condition of the Institution</li>
                        <li>Adequacy of ALL</li>
                        <li>Access to Capital Markets/Other Sources of Capital</li>
                        <li>Bank Strategic Plan</li>
                        <li>Anticipated Growth</li>
                        <li>Dividend Plans</li>
                        <li>Local Economic Conditions</li>
                        <li>Information Technology/Cybersecurity</li>

                    </ul>
                </td>
                <td>
                    Does the Bank have the Right Regulatory Leadership at each of the Board, Management, and Employee Base Level(s) that ensures the Bank will achieve the targeted Asset Quality Outcomes?
                </td>
                <td>
                    Does the Bank allocate Sufficient Regulatory Resources that ensure the Bank will achieve the targeted Asset Quality Outcomes?
                </td>
            </tr>
            <tr>
                <td>
                    Does the Bank have Accountable Regulatory Processes that ensure the Bank will achieve the targeted Asset Quality Outcomes?
                </td>
                <td>
                    Does the Bank have an Effective Regulatory Culture that ensures the Bank will achieve the targeted Asset Quality Outcomes?
                </td>
            </tr>
            <tr>
                <td rowspan="2" colspan="2">
                    <ul>
                        <li>Scoring</li>
                        <li>
                            0 = No Chance of Achieving Outcomes
                        </li>
                        <li>1 = Very Low Likelihood of Achieving Outcomes</li>
                        <li>2 = Low Likelihood of Achieving Outcomes</li>
                        <li>3 = 50/50 Likelihood of Achieving Outcomes</li>
                        <li>4 = Good Level of Understanding/Knowledge</li>
                        <li>5 = Expert Level of Understanding/Knowledge</li>
                    </ul>
                </td>
                <td>
                    Regulatory Leadership:
                    @Html.EditorFor(model => model.RegulatoryLeadership, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.RegulatoryLeadership, "", new { @class = "text-danger" })

                </td>
                <td>
                    Regulatory Resources:
                    @Html.EditorFor(model => model.RegulatoryResources, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.RegulatoryResources, "", new { @class = "text-danger" })

                </td>
                <td>
                    Regulatory Processes:
                    @Html.EditorFor(model => model.RegulatoryProcesses, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.RegulatoryProcesses, "", new { @class = "text-danger" })

                </td>
                <td>
                    Regulatory Culture:

                    @Html.EditorFor(model => model.RegulatoryCulture, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.RegulatoryCulture, "", new { @class = "text-danger" })

                </td>
            </tr>
            <tr>
                <td colspan="4">
                    Composite Score:

                    @Html.EditorFor(model => model.TotalAssetRegulatoryScore, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.TotalAssetRegulatoryScore, "", new { @class = "text-danger" })

                </td>
            </tr>
        </table>
        @Html.ActionLink("Next", "ManagementEffectivenessCapitalAssessment", "Camel")
    </div>
}

EthicsCap2/Views/Camel/AssetQualityAssessment.cshtml
@model EthicsCap2.Models.Camels.AssetQualityAssessment
@{
    ViewData["Title"] = "Asset Quality Assessment";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <h1>Asset Quality Assessment</h1>

    <div class="form-horizontal">
        <h2>Asset Quality</h2>
        <hr />
        <table class="table table-bordered table-responsive table-hover d-xl-table">

            <tr>
                <th rowspan="1" colspan="2" align="center">Targeted Regulatory Outcomes</th>
                <th rowspan="1" colspan="1">Regulatory Knowledge Question(s)</th>
                <th rowspan="1" colspan="1">Assessment Scoring</th>
            </tr>
            <tr>
                <td rowspan="1" align="center">
                    Capital Adequacy Rating:
                    <br />
                    <br />
                    @Html.EditorFor(model => model.CapitalAdequacyRating, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CapitalAdequacyRating, "", new { @class = "text-danger" })
                </td>
                <td rowspan="1" align="center">
                    Targeted Financial/Risk Outcomes:
                    <br />
                    <br />
                    Adversely Classified Items Ratio                                >
                    @Html.EditorFor(model => model.AdverselyClassifiedItemsRatio, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.AdverselyClassifiedItemsRatio, "", new { @class = "text-danger" })

                </td>
                <td>
                    1) How well do you understand the specific Ratings Evaluation Factors for achieving the targeted Exam Rating for Asset Quality?
                </td>
                <td>
                    @Html.EditorFor(model => model.AssetQualityQuestion1, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.AssetQualityQuestion1, "", new { @class = "text-danger" })
                </td>
            </tr>
            <tr>
                <td rowspan="2" colspan="2">
                    <ul>
                        <li>
                            Regulatory Evaluation Factors for Determining Asset Quality Rating:
                        </li>
                        <li>Underwriting and Credit Administration</li>
                        <li>Level and Trend of Problem Assets</li>
                        <li>Adequacy of ALL Reserves</li>
                        <li>Asset Risk Concentrations</li>
                        <li> Management Expertise to Identify, Measure, and Control Credit Risk</li>
                    </ul>

                </td>
                <td>
                    2) How well do you understand the ACI Ratio of your Bank; how it is calculated; and what specific assumptions are made in calculating it?
                </td>
                <td>
                    @Html.EditorFor(model => model.AssetQualityQuestion2, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.AssetQualityQuestion2, "", new { @class = "text-danger" })
                </td>
            </tr>
            <tr>
                <td>
                    3) How well do you understand the Bank’s overall Risk Appetite and each of the Risk Tolerance Limits regrading Credit Risk?
                </td>
                <td>
                    @Html.EditorFor(model => model.AssetQualityQuestion3, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.AssetQualityQuestion3, "", new { @class = "text-danger" })
                </td>
            </tr>
            <tr>
                <td rowspan="2" colspan="3">
                    <ul>
                        <li>Scoring</li>
                        <li>0 = Do Not Understand or Know</li>
                        <li>1 = Very Low Level of Understanding/Knowledge</li>
                        <li>2 = Low Level of Understanding/Knowledge</li>
                        <li>3 = Average Level of Understanding/Knowledge</li>
                        <li>4 = Good Level of Understanding/Knowledge</li>
                        <li>5 = Expert Level of Understanding/Knowledge</li>
                    </ul>
                </td>
                <td>
                    Composite Average:
                    @Html.EditorFor(model => model.CompositeAverage, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CompositeAverage, "", new { @class = "text-danger" })

                </td>
            </tr>

        </table>
        @Html.ActionLink("Next", "ManagementEffectivenessAssessment", "Camel")
    </div>
}

EthicsCap2/Views/Camel/CalculatingRegulatoryIQ.cshtml
@{
    ViewData["Title"] = "CalculatingRegulatoryIQ";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Calculating Regulatory IQ</h1>
<head>
    <style type="text/css">
       td {
  width: 50px;
  border: 15px solid green;
  padding: 50px;
  margin: 20px;
}
     
    </style>
</head>


<div class="btn-group-horizontal">
    <div >
        <table>
            <tr>
                <th colspan="2">
                    Regulatory
                    Alignment Score

                </th>
                <th colspan="2">
                    Regulatory
                    Knowledge Score
                </th>
                <th colspan="2">
                    Regulatory Capital Score
                </th>
                <th colspan="2">
                    Regulatory IQ Score
                </th>
            <tr>
                <td>12</td>
                <th><font size="+10">X</font></th>
                <td>12</td>
                <th><font size="+10">X</font></th>
                <td>12</td>
                <th><font size="+10">=</font></th>
                <td>576</td>
            </tr>
        </table>
    </div>
</div>
<div>
    <img src="~/images/RegIQTable.png" />
</div>
<div>
    @Html.ActionLink("Done", "Index", "Home")
</div>